export type CategoryType =
  | "food"
  | "drinks"
  | "meat"
  | "dairy products"
  | "household goods"
  | "household chemicals"
  | "cosmetics"
  | "bio food"
  | "snacks"
  | "confectionery"
  | "seafood"
  | "frozen food"
  | "baked goods"
  | "fruits and vegetables"
  | "beverages"
  | "pet supplies"
  | "baby products"
  | "health supplements"
  | "electronics"
  | "personal hygiene"
  | "stationery"
  | "home decor"
  | "other";